import {
  Apple,
  Baby,
  Car,
  Dumbbell,
  Footprints,
  Layers,
  Palette,
  Sparkles,
  UserRound,
  Briefcase,
  Coffee,
  Gem,
  Gift,
  Headphones,
  HeartPulse,
  House,
  Megaphone,
  NotebookPen,
  Package,
  PartyPopper,
  PenLine,
  Plane,
  Shirt,
  ShoppingBag,
  Trophy,
  TreePine,
  Umbrella,
  Watch,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  // Единое дерево (Oasis)
  selection: Layers,
  "nastraivaemie-nabori": Sparkles,
  "podarochnie-nabori": Gift,
  "avtomobilnie-aksessuari": Car,
  "delovie-podarki": Trophy,
  "dlya-doma": House,
  "dlya-otdiha": TreePine,
  "dlya-puteshestvii": Plane,
  "dlya-sporta": Dumbbell,
  "zhenskie-aksessuari": Gem,
  zonti: Umbrella,
  "kuhnya-i-posuda": Coffee,
  "lichnie-aksessuari": Watch,
  "muzhskie-aksessuari": UserRound,
  tekstil: Shirt,
  "ofisnie-aksessuari": NotebookPen,
  "pishuschie-instrumenti": PenLine,
  "sedobnie-podarki": Apple,
  "tovari-dlya-detei": Baby,
  tehnologii: Headphones,
  kastomizaciya: Palette,
  prazdniki: PartyPopper,
  obuv: Footprints,
  "promo-odezhda": Shirt,
  "podarochnye-nabory": Gift,
  ejednevniki: NotebookPen,
  posuda: Coffee,
  elektronika: Headphones,
  sumki: ShoppingBag,
  upakovka: Package,
  dom: House,
  ruchki: PenLine,
  zonty: Umbrella,
  personalnye: Briefcase,
  nagrady: Trophy,
  "puteshestvie-i-otdy-x": Plane,
  promo: Megaphone,
  vip: Gem,
  "suveniry-k-prazdnikam": PartyPopper,
  "novyy-god": TreePine,
  chasy: Watch,
  "uhod-i-zdorovie": HeartPulse,
  detyam: Baby,
};

export const categoryIcon = (id: string): LucideIcon => icons[id] ?? Package;
