import {
  Baby,
  Briefcase,
  Coffee,
  Gem,
  Gift,
  Headphones,
  HeartPulse,
  House,
  Megaphone,
  NotebookPen,
  Package,
  PartyPopper,
  PenLine,
  Plane,
  Shirt,
  ShoppingBag,
  Trophy,
  TreePine,
  Umbrella,
  Watch,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "promo-odezhda": Shirt,
  "podarochnye-nabory": Gift,
  ejednevniki: NotebookPen,
  posuda: Coffee,
  elektronika: Headphones,
  sumki: ShoppingBag,
  upakovka: Package,
  dom: House,
  ruchki: PenLine,
  zonty: Umbrella,
  personalnye: Briefcase,
  nagrady: Trophy,
  "puteshestvie-i-otdy-x": Plane,
  promo: Megaphone,
  vip: Gem,
  "suveniry-k-prazdnikam": PartyPopper,
  "novyy-god": TreePine,
  chasy: Watch,
  "uhod-i-zdorovie": HeartPulse,
  detyam: Baby,
};

export const categoryIcon = (id: string): LucideIcon => icons[id] ?? Package;
