import type { Category, Product } from "./types";

export const popularCategories: Category[] = [
  { id: "novyy-god", title: "Новогодние подарки", href: "/catalog/novyy-god", image: "/images/categories/novyy-god.webp" },
  { id: "suveniry-k-prazdnikam", title: "Сувениры к праздникам", href: "/catalog/suveniry-k-prazdnikam", image: "/images/categories/prazdniki.webp" },
  { id: "promo-odezhda", title: "Одежда", href: "/catalog/promo-odezhda", image: "/images/categories/odezhda.webp" },
  { id: "podarochnye-nabory", title: "Подарочные наборы", href: "/catalog/podarochnye-nabory", image: "/images/categories/nabory.webp" },
  { id: "ejednevniki", title: "Ежедневники и блокноты", href: "/catalog/ejednevniki", image: "/images/categories/ezhednevniki.webp" },
  { id: "upakovka", title: "Упаковка", href: "/catalog/upakovka", image: "/images/categories/upakovka.webp" },
  { id: "posuda", title: "Посуда", href: "/catalog/posuda", image: "/images/categories/posuda.webp" },
  { id: "elektronika", title: "Электроника", href: "/catalog/elektronika", image: "/images/categories/elektronika.webp" },
  { id: "ruchki", title: "Ручки с логотипом", href: "/catalog/ruchki", image: "/images/categories/ruchki.webp" },
  { id: "sumki", title: "Сумки", href: "/catalog/sumki", image: "/images/categories/sumki.webp" },
  { id: "zonty", title: "Зонты с логотипом", href: "/catalog/zonty", image: "/images/categories/zonty.webp" },
  { id: "personalnye", title: "Корпоративные подарки", href: "/catalog/personalnye", image: "/images/categories/korporativnye.webp" },
  { id: "nagrady", title: "Награды", href: "/catalog/nagrady", image: "/images/categories/nagrady.webp" },
  { id: "dom", title: "Дом", href: "/catalog/dom", image: "/images/categories/dom.webp" },
  { id: "puteshestvie-i-otdy-x", title: "Путешествие и отдых", href: "/catalog/puteshestvie-i-otdy-x", image: "/images/categories/otdyh.webp" },
  { id: "vip", title: "Элитные подарки", href: "/catalog/vip", image: "/images/categories/elitnye.webp" },
  { id: "chasy", title: "Часы и метеостанции", href: "/catalog/chasy", image: "/images/categories/chasy.webp" },
  { id: "promo", title: "Промо-сувениры", href: "/catalog/promo", image: "/images/categories/promo.webp" },
  { id: "uhod-i-zdorovie", title: "Уход и здоровье", href: "/catalog/uhod-i-zdorovie", image: "/images/categories/zdorovie.webp" },
  { id: "detyam", title: "Детям", href: "/catalog/detyam", image: "/images/categories/detyam.webp" },
];

export const newProducts: Product[] = [
  {
    id: "29797004",
    title: "Ручка шариковая New Hotel Chrome, матовая синяя",
    sku: "27078.40",
    priceFrom: 60,
    currency: "RUB",
    image: "/images/products/nov-29797004.webp",
    url: "/catalog/ruchki/ruchki-metallicheskie/item-ruchka-sharikovaya-new-hotel-chrome-matovaya-sinyaya-2707840",
    stock: 82200,
    isNew: true,
  },
  {
    id: "29612363",
    title: "Брелок-фонарик Sparkey, черный",
    sku: "18755.30",
    priceFrom: 180,
    currency: "RUB",
    image: "/images/products/nov-29612363.webp",
    url: "/catalog/promo/promo-plastikovye-brelki/item-brelok-fonarik-sparkey-chernyj-1875530",
    stock: 1439,
    isNew: true,
  },
  {
    id: "29798885",
    title: "Антистресс «Теннисный мяч»",
    sku: "20399.01",
    priceFrom: 130,
    currency: "RUB",
    image: "/images/products/nov-29798885.webp",
    url: "/catalog/promo/promo-antistressy/item-antistress-tennisnyj-myach-2039901",
    stock: 2719,
    isNew: true,
  },
  {
    id: "29799421",
    title: "Коробка «Домик», M, белая",
    sku: "26020.60",
    priceFrom: 132,
    currency: "RUB",
    image: "/images/products/nov-29799421.webp",
    url: "/catalog/novyy-god/upakovka-dlya-novogodnih-podarkov/item-korobka-domik-m-belaya-2602060",
    stock: 885,
    isNew: true,
  },
  {
    id: "29796969",
    title: "Ручка шариковая Carton Plus, ver.2, черная",
    sku: "19670.30",
    priceFrom: 24,
    currency: "RUB",
    image: "/images/products/nov-29796969.webp",
    url: "/catalog/ruchki/ruchki-derevyannye/item-ruchka-sharikovaya-carton-plus-ver2-chernaya-1967030",
    stock: 3718,
    isNew: true,
  },
  {
    id: "29611169",
    title: "Застежка-карабин Snap Hook, L, черная",
    sku: "18736.30",
    priceFrom: 61,
    currency: "RUB",
    image: "/images/products/nov-29611169.webp",
    url: "/catalog/promo-odezhda/10063/item-zastezhka-karabin-snap-hook-l-chernaya-1873630",
    stock: 4887,
    isNew: true,
  },
];
