import type { CatalogNode, Category, Product } from "./types";

export const popularCategories: Category[] = [
  { id: "novyy-god", title: "Новогодние подарки", href: "/catalog/novyy-god", image: "/images/categories/novyy-god.webp" },
  { id: "suveniry-k-prazdnikam", title: "Сувениры к праздникам", href: "/catalog/suveniry-k-prazdnikam", image: "/images/categories/prazdniki.webp" },
  { id: "promo-odezhda", title: "Одежда", href: "/catalog/promo-odezhda", image: "/images/categories/odezhda.webp" },
  { id: "podarochnye-nabory", title: "Подарочные наборы", href: "/catalog/podarochnye-nabory", image: "/images/categories/nabory.webp" },
  { id: "ejednevniki", title: "Ежедневники и блокноты", href: "/catalog/ejednevniki", image: "/images/categories/ezhednevniki.webp" },
  { id: "upakovka", title: "Упаковка", href: "/catalog/upakovka", image: "/images/categories/upakovka.webp" },
  { id: "posuda", title: "Посуда", href: "/catalog/posuda", image: "/images/categories/posuda.webp" },
  { id: "elektronika", title: "Электроника", href: "/catalog/elektronika", image: "/images/categories/elektronika.webp" },
  { id: "ruchki", title: "Ручки с логотипом", href: "/catalog/ruchki", image: "/images/categories/ruchki.webp" },
  { id: "sumki", title: "Сумки", href: "/catalog/sumki", image: "/images/categories/sumki.webp" },
  { id: "zonty", title: "Зонты с логотипом", href: "/catalog/zonty", image: "/images/categories/zonty.webp" },
  { id: "personalnye", title: "Корпоративные подарки", href: "/catalog/personalnye", image: "/images/categories/korporativnye.webp" },
  { id: "nagrady", title: "Награды", href: "/catalog/nagrady", image: "/images/categories/nagrady.webp" },
  { id: "dom", title: "Дом", href: "/catalog/dom", image: "/images/categories/dom.webp" },
  { id: "puteshestvie-i-otdy-x", title: "Путешествие и отдых", href: "/catalog/puteshestvie-i-otdy-x", image: "/images/categories/otdyh.webp" },
  { id: "vip", title: "Элитные подарки", href: "/catalog/vip", image: "/images/categories/elitnye.webp" },
  { id: "chasy", title: "Часы и метеостанции", href: "/catalog/chasy", image: "/images/categories/chasy.webp" },
  { id: "promo", title: "Промо-сувениры", href: "/catalog/promo", image: "/images/categories/promo.webp" },
  { id: "uhod-i-zdorovie", title: "Уход и здоровье", href: "/catalog/uhod-i-zdorovie", image: "/images/categories/zdorovie.webp" },
  { id: "detyam", title: "Детям", href: "/catalog/detyam", image: "/images/categories/detyam.webp" },
];

export const newProducts: Product[] = [
  {
    id: "29797004",
    title: "Ручка шариковая New Hotel Chrome, матовая синяя",
    sku: "27078.40",
    priceFrom: 60,
    currency: "RUB",
    image: "/images/products/nov-29797004.webp",
    url: "/catalog/ruchki/ruchki-metallicheskie/item-ruchka-sharikovaya-new-hotel-chrome-matovaya-sinyaya-2707840",
    stock: 82200,
    isNew: true,
  },
  {
    id: "29612363",
    title: "Брелок-фонарик Sparkey, черный",
    sku: "18755.30",
    priceFrom: 180,
    currency: "RUB",
    image: "/images/products/nov-29612363.webp",
    url: "/catalog/promo/promo-plastikovye-brelki/item-brelok-fonarik-sparkey-chernyj-1875530",
    stock: 1439,
    isNew: true,
  },
  {
    id: "29798885",
    title: "Антистресс «Теннисный мяч»",
    sku: "20399.01",
    priceFrom: 130,
    currency: "RUB",
    image: "/images/products/nov-29798885.webp",
    url: "/catalog/promo/promo-antistressy/item-antistress-tennisnyj-myach-2039901",
    stock: 2719,
    isNew: true,
  },
  {
    id: "29799421",
    title: "Коробка «Домик», M, белая",
    sku: "26020.60",
    priceFrom: 132,
    currency: "RUB",
    image: "/images/products/nov-29799421.webp",
    url: "/catalog/novyy-god/upakovka-dlya-novogodnih-podarkov/item-korobka-domik-m-belaya-2602060",
    stock: 885,
    isNew: true,
  },
  {
    id: "29796969",
    title: "Ручка шариковая Carton Plus, ver.2, черная",
    sku: "19670.30",
    priceFrom: 24,
    currency: "RUB",
    image: "/images/products/nov-29796969.webp",
    url: "/catalog/ruchki/ruchki-derevyannye/item-ruchka-sharikovaya-carton-plus-ver2-chernaya-1967030",
    stock: 3718,
    isNew: true,
  },
  {
    id: "29611169",
    title: "Застежка-карабин Snap Hook, L, черная",
    sku: "18736.30",
    priceFrom: 61,
    currency: "RUB",
    image: "/images/products/nov-29611169.webp",
    url: "/catalog/promo-odezhda/10063/item-zastezhka-karabin-snap-hook-l-chernaya-1873630",
    stock: 4887,
    isNew: true,
  },
];

// Демо: цена распродажи = −20% от реальной цены (oldPrice); позже — из админки/API складов.
export const saleProducts: Product[] = [
  {
    id: "29796968",
    title: "Ручка шариковая Tippo, зеленая",
    sku: "20566.90",
    priceFrom: 26,
    oldPrice: 33,
    currency: "RUB",
    image: "/images/products/nov-29796968.webp",
    url: "/catalog/ruchki/ruchki-plastikovye/item-ruchka-sharikovaya-tippo-zelenaya-2056690",
    stock: 9794,
  },
  {
    id: "29798882",
    title: "Антистресс «Волейбольный мяч», белый",
    sku: "20684.60",
    priceFrom: 104,
    oldPrice: 130,
    currency: "RUB",
    image: "/images/products/nov-29798882.webp",
    url: "/catalog/promo/promo-antistressy/item-antistress-volejbolnyj-myach-belyj-2068460",
    stock: 2924,
  },
  {
    id: "29799419",
    title: "Коробка «Домик», S, белая",
    sku: "26019.60",
    priceFrom: 80,
    oldPrice: 100,
    currency: "RUB",
    image: "/images/products/nov-29799419.webp",
    url: "/catalog/novyy-god/upakovka-dlya-novogodnih-podarkov/item-korobka-domik-s-belaya-2601960",
    stock: 783,
  },
  {
    id: "29610924",
    title: "Подвеска «Звезда», 3D-печать, оранжевая",
    sku: "23318.20",
    priceFrom: 140,
    oldPrice: 175,
    currency: "RUB",
    image: "/images/products/nov-29610924.webp",
    url: "/catalog/promo/promo-plastikovye-brelki/item-podveska-zvezda-3d-pechat-oranzhevaya-2331820",
    stock: 216,
  },
  {
    id: "29601649",
    title: "Ремувка на кнопке Tohu, черная",
    sku: "19552.30",
    priceFrom: 144,
    oldPrice: 180,
    currency: "RUB",
    image: "/images/products/nov-29601649.webp",
    url: "/catalog/promo/promo-plastikovye-brelki/item-remuvka-na-knopke-tohu-chernaya-1955230",
    stock: 151,
  },
  {
    id: "29798888",
    title: "Антистресс «Контейнер», серый",
    sku: "23035.10",
    priceFrom: 159,
    oldPrice: 199,
    currency: "RUB",
    image: "/images/products/nov-29798888.webp",
    url: "/catalog/promo/promo-antistressy/item-antistress-kontejner-seryj-2303510",
    stock: 4409,
  },
];

export const catalogTree: CatalogNode[] = [
  {
    id: "promo-odezhda",
    title: "Одежда",
    href: "/catalog/promo-odezhda",
    children: [
      { title: "Футболки", href: "/catalog/promo-odezhda/futbolki" },
      { title: "Поло", href: "/catalog/promo-odezhda/polo" },
      { title: "Рубашки", href: "/catalog/promo-odezhda/rubashki" },
      { title: "Джемперы", href: "/catalog/promo-odezhda/odejda-jumper" },
      { title: "Брюки и шорты", href: "/catalog/promo-odezhda/bryuki-i-shorty" },
      { title: "Куртки и жилеты", href: "/catalog/promo-odezhda/vetrovki-kurtki-zhilety" },
      { title: "Толстовки", href: "/catalog/promo-odezhda/odejda-tolstovki" },
      { title: "Спортивная одежда", href: "/catalog/promo-odezhda/odejda-sportivnaya-odezhda" },
      { title: "Шапки и перчатки", href: "/catalog/promo-odezhda/shapki-sharfy-perchatki" },
      { title: "Бейсболки и панамы", href: "/catalog/promo-odezhda/odejda-kepki" },
      { title: "Ремни и носки", href: "/catalog/promo-odezhda/remni" },
      { title: "Солнцезащитные очки", href: "/catalog/promo-odezhda/4168" },
      { title: "Рабочая одежда", href: "/catalog/promo-odezhda/rabochaya-odezhda" },
      { title: "Халаты и фартуки", href: "/catalog/promo-odezhda/fartuki-s-logotipom" },
      { title: "Аксессуары", href: "/catalog/promo-odezhda/odejda-aksessuary" },
      { title: "Для брендирования", href: "/catalog/promo-odezhda/10063" },
    ],
  },
  {
    id: "podarochnye-nabory",
    title: "Подарочные наборы",
    href: "/catalog/podarochnye-nabory",
    children: [
      { title: "Бизнес наборы", href: "/catalog/podarochnye-nabory/personalnye-podarochnye-nabory" },
      { title: "Наборы с термокружками", href: "/catalog/podarochnye-nabory/nabory-s-termostakanami-termosami" },
      { title: "Наборы для сыра", href: "/catalog/podarochnye-nabory/nabory-dlya-sy-ra" },
      { title: "Продуктовые наборы", href: "/catalog/podarochnye-nabory/s-podarochnye-produktovye-nabory" },
      { title: "Банные наборы", href: "/catalog/podarochnye-nabory/nabory-s-kosmetikoi" },
      { title: "Чайные наборы", href: "/catalog/podarochnye-nabory/chajny-e-i-kofejny-e-nabory-" },
      { title: "Спортивные наборы", href: "/catalog/podarochnye-nabory/sportivny-e-nabory-" },
      { title: "Наборы для алкоголя", href: "/catalog/podarochnye-nabory/dom-vinnye-nabory" },
      { title: "Элитные наборы", href: "/catalog/podarochnye-nabory/elitnye-nabory" },
      { title: "Наборы для мужчин", href: "/catalog/podarochnye-nabory/muzhskie-nabory-" },
      { title: "Наборы для женщин", href: "/catalog/podarochnye-nabory/nabory-s-platkami" },
      { title: "Наборы для детей", href: "/catalog/podarochnye-nabory/2438" },
      { title: "Кухонные наборы", href: "/catalog/podarochnye-nabory/kuxonny-e-nabory-" },
      { title: "Наборы для дома", href: "/catalog/podarochnye-nabory/2733" },
      { title: "Подарочные наборы с антистрессами", href: "/catalog/podarochnye-nabory/33457" },
      { title: "Спортивные наборы", href: "/catalog/podarochnye-nabory/59591" },
      { title: "Подарочные наборы для мужчин", href: "/catalog/podarochnye-nabory/59585" },
      { title: "Подарочные наборы изделий из кожи с логотипом", href: "/catalog/podarochnye-nabory/59594" },
      { title: "Подарочные наборы с термокружками", href: "/catalog/podarochnye-nabory/59588" },
      { title: "Подарочные наборы с аккумуляторами", href: "/catalog/podarochnye-nabory/59597" },
      { title: "Подарочные наборы для женщин", href: "/catalog/podarochnye-nabory/59589" },
      { title: "Подарочные наборы с зонтами", href: "/catalog/podarochnye-nabory/22623" },
      { title: "Подарочные наборы с мультитулами", href: "/catalog/podarochnye-nabory/59586" },
      { title: "Подарочные наборы с пледами", href: "/catalog/podarochnye-nabory/59595" },
      { title: "Кухонные подарочные наборы", href: "/catalog/podarochnye-nabory/59584" },
      { title: "Наборы для выращивания растений", href: "/catalog/podarochnye-nabory/59598" },
      { title: "Подарочные наборы для детей", href: "/catalog/podarochnye-nabory/59592" },
      { title: "Дорожные наборы для путешествий", href: "/catalog/podarochnye-nabory/59593" },
      { title: "Подарочные наборы с кружками", href: "/catalog/podarochnye-nabory/59587" },
      { title: "Подарочные наборы с флешками", href: "/catalog/podarochnye-nabory/59596" },
      { title: "Подарочные наборы с бутылками для воды", href: "/catalog/podarochnye-nabory/59590" },
    ],
  },
  {
    id: "ejednevniki",
    title: "Ежедневники и блокноты",
    href: "/catalog/ejednevniki",
    children: [
      { title: "Датированные", href: "/catalog/ejednevniki/datirovanny-e" },
      { title: "Недатированные", href: "/catalog/ejednevniki/nedatirovanny-e" },
      { title: "Блокноты", href: "/catalog/ejednevniki/bloknoty" },
      { title: "Планинги", href: "/catalog/ejednevniki/planingi" },
      { title: "Наборы", href: "/catalog/ejednevniki/nabori-s-ejednevnikami" },
      { title: "Упаковка", href: "/catalog/ejednevniki/ejednevniki-upakovka" },
      { title: "Ежедневники с логотипом", href: "/catalog/ejednevniki/59573" },
    ],
  },
  {
    id: "posuda",
    title: "Посуда",
    href: "/catalog/posuda",
    children: [
      { title: "Термокружки", href: "/catalog/posuda/posuda-termostakany" },
      { title: "Термосы", href: "/catalog/posuda/termosy-" },
      { title: "Бутылки и фляги", href: "/catalog/posuda/flyagi" },
      { title: "Стаканы и бокалы", href: "/catalog/posuda/posuda-stakany" },
      { title: "Кружки и бокалы для пива", href: "/catalog/posuda/3952" },
      { title: "Аксессуары для алкоголя", href: "/catalog/posuda/aksessuary-dlya-alkogolya" },
      { title: "Графины и чайники", href: "/catalog/posuda/grafiny" },
      { title: "Ланч-боксы", href: "/catalog/posuda/lanchboksy-" },
      { title: "Тарелки", href: "/catalog/posuda/nabory-tarelok" },
      { title: "Кружки", href: "/catalog/posuda/posuda-krujki" },
      { title: "Наборы и сервировка", href: "/catalog/posuda/posuda-nabory-posudy" },
      { title: "Термосы с логотипом", href: "/catalog/posuda/59554" },
      { title: "Термосы для еды с логотипом", href: "/catalog/posuda/59562" },
      { title: "Многоразовые стаканы с крышкой", href: "/catalog/posuda/59560" },
      { title: "Барные аксессуары", href: "/catalog/posuda/59563" },
      { title: "Кофейные наборы", href: "/catalog/posuda/59557" },
      { title: "Чайные наборы", href: "/catalog/posuda/59558" },
      { title: "Разделочные доски", href: "/catalog/posuda/59564" },
      { title: "Костеры с логотипом", href: "/catalog/posuda/59561" },
      { title: "Мельницы для специй", href: "/catalog/posuda/59555" },
      { title: "Фляжки с логотипом", href: "/catalog/posuda/59556" },
      { title: "Пивные бокалы с логотипом", href: "/catalog/posuda/59559" },
    ],
  },
  {
    id: "elektronika",
    title: "Электроника",
    href: "/catalog/elektronika",
    children: [
      { title: "Флешки", href: "/catalog/elektronika/fleshki" },
      { title: "Портативные аккумуляторы", href: "/catalog/elektronika/elektronika-universalnye-akkumulyatory" },
      { title: "Зарядные устройства", href: "/catalog/elektronika/elektronika-zaryadniki" },
      { title: "Колонки и наушники", href: "/catalog/elektronika/elektronika-portativnye-kolonki" },
      { title: "Чехлы для телефонов", href: "/catalog/elektronika/3775" },
      { title: "MP3 плееры", href: "/catalog/elektronika/4171" },
      { title: "Смарт-браслеты", href: "/catalog/elektronika/smart-braslety" },
      { title: "Мобильные аксессуары", href: "/catalog/elektronika/elektronika-aksessuary-dlya-mobilnyh-ustroystv" },
      { title: "Бытовая техника", href: "/catalog/elektronika/elektronika-bytovaya-tehnika" },
      { title: "Лампы", href: "/catalog/elektronika/lampy" },
      { title: "Увлажнители воздуха с логотипом", href: "/catalog/elektronika/59568" },
      { title: "Внешние аккумуляторы со встроенными кабелями", href: "/catalog/elektronika/50742" },
      { title: "Лампы и светильники", href: "/catalog/elektronika/59567" },
    ],
  },
  {
    id: "sumki",
    title: "Сумки",
    href: "/catalog/sumki",
    children: [
      { title: "Рюкзаки и сумки-мешки", href: "/catalog/sumki/sumki-ryukzaki" },
      { title: "Сумки для покупок", href: "/catalog/sumki/sumki-dlya-pokupok" },
      { title: "Пляжные и для пикника", href: "/catalog/sumki/plyazhny-e-sumki" },
      { title: "Сумки для документов", href: "/catalog/sumki/sumki-konferenc-sumki" },
      { title: "Поясные и через плечо", href: "/catalog/sumki/poyasny-e-sumki" },
      { title: "Косметички и несессеры", href: "/catalog/sumki/sumki-nesessery" },
      { title: "Спортивные сумки", href: "/catalog/sumki/sumki-sportivnye" },
      { title: "Сумки для ноутбука и планшета", href: "/catalog/sumki/sumki-sumki-dlya-noutbuka" },
      { title: "Чемоданы и портфели", href: "/catalog/sumki/sumki-chemodany" },
      { title: "Дорожные сумки", href: "/catalog/sumki/sumki-dorojnye" },
      { title: "Рюкзаки-холодильники", href: "/catalog/sumki/11788" },
      { title: "Поясные сумки", href: "/catalog/sumki/59565" },
      { title: "Дорожные сумки", href: "/catalog/sumki/11039" },
      { title: "Шоперы с логотипом", href: "/catalog/sumki/59566" },
      { title: "Сумки", href: "/catalog/sumki/11411" },
      { title: "Компактные сумки", href: "/catalog/sumki/11043" },
      { title: "Городские сумки", href: "/catalog/sumki/11412" },
    ],
  },
  {
    id: "upakovka",
    title: "Упаковка",
    href: "/catalog/upakovka",
    children: [
      { title: "Пакеты и коробки", href: "/catalog/upakovka/podarochnye-pakety" },
      { title: "Из металла", href: "/catalog/upakovka/iz-metalla" },
      { title: "Из дерева", href: "/catalog/upakovka/iz-dereva" },
      { title: "Из картона", href: "/catalog/upakovka/iz-kartona" },
      { title: "Из текстиля", href: "/catalog/upakovka/iz-tekstilya" },
      { title: "Наполнители", href: "/catalog/upakovka/napolniteli-dlya-upakovki" },
      { title: "Подарочные коробки", href: "/catalog/upakovka/59583" },
    ],
  },
  {
    id: "dom",
    title: "Дом",
    href: "/catalog/dom",
    children: [
      { title: "Пледы", href: "/catalog/dom/3940" },
      { title: "Полотенца", href: "/catalog/dom/polotencza-s-logotipom" },
      { title: "Подушки", href: "/catalog/dom/3941" },
      { title: "Кухонные принадлежности", href: "/catalog/dom/dom-kuhonnye-prisposobleniya" },
      { title: "Интерьерные подарки", href: "/catalog/dom/dom-interernye-podarki" },
      { title: "Статуэтки и скульптуры", href: "/catalog/dom/dom-statuetki" },
      { title: "Вазы и шкатулки", href: "/catalog/dom/dom-shkatulki" },
      { title: "Для ухода за обувью", href: "/catalog/dom/dom-nabory-dlya-uhoda-za-obuvyu" },
      { title: "Фоторамки", href: "/catalog/dom/dom-fotoramki-fotoalbomy" },
      { title: "Косметика", href: "/catalog/dom/kosmetika-i-parfyumeriya" },
      { title: "Свечи", href: "/catalog/dom/dom-dekorativnye-svechi" },
      { title: "Садовые аксессуары", href: "/catalog/dom/2433" },
      { title: "Для бани и сауны", href: "/catalog/dom/3939" },
      { title: "Горшки", href: "/catalog/dom/gorshki" },
      { title: "Пледы", href: "/catalog/dom/59657" },
      { title: "Ароматические диффузоры с логотипом", href: "/catalog/dom/12255" },
      { title: "Свечи", href: "/catalog/dom/35453" },
      { title: "Аксессуары и средства для ухода", href: "/catalog/dom/59655" },
      { title: "Игрушки", href: "/catalog/dom/59656" },
    ],
  },
  {
    id: "ruchki",
    title: "Ручки с логотипом",
    href: "/catalog/ruchki",
    children: [
      { title: "Пластиковые ручки", href: "/catalog/ruchki/ruchki-plastikovye" },
      { title: "Металлические ручки", href: "/catalog/ruchki/ruchki-metallicheskie" },
      { title: "Бумажные и эко ручки", href: "/catalog/ruchki/ruchki-derevyannye" },
      { title: "Ручки-стилусы", href: "/catalog/ruchki/2442" },
      { title: "Карандаши", href: "/catalog/ruchki/ruchki-karandashi" },
      { title: "Наборы с ручками", href: "/catalog/ruchki/ruchki-nabory-ruchek" },
      { title: "Футляры для ручек", href: "/catalog/ruchki/futlyary-dlya-ruchek" },
      { title: "Элитные ручки", href: "/catalog/ruchki/5717" },
      { title: "Канцелярия", href: "/catalog/ruchki/5950" },
      { title: "Наборы для рисования", href: "/catalog/ruchki/49273" },
      { title: "Карандаши вечные", href: "/catalog/ruchki/10986" },
    ],
  },
  {
    id: "zonty",
    title: "Зонты с логотипом",
    href: "/catalog/zonty",
    children: [
      { title: "Складные зонты", href: "/catalog/zonty/zonty-skladnye-zonty" },
      { title: "Зонты-трости", href: "/catalog/zonty/zonty-zonty-trosti" },
      { title: "Дождевики", href: "/catalog/zonty/dozhdeviki" },
      { title: "Оригинальные зонты", href: "/catalog/zonty/zonty-neobychnye-zonty" },
    ],
  },
  {
    id: "personalnye",
    title: "Корпоративные подарки",
    href: "/catalog/personalnye",
    children: [
      { title: "Картхолдеры", href: "/catalog/personalnye/korporativnye-cartholdery" },
      { title: "Кошельки", href: "/catalog/personalnye/personalnye-koshelki" },
      { title: "Ключницы", href: "/catalog/personalnye/2536" },
      { title: "Обложки для документов", href: "/catalog/personalnye/personalnye-oblojki-dlya-dokumentov" },
      { title: "Дорожные органайзеры", href: "/catalog/personalnye/personalnye-dorojnye-organayzery" },
      { title: "Папки, портфели", href: "/catalog/personalnye/personalnye-papki-bloknoty" },
      { title: "Аксессуары", href: "/catalog/personalnye/2535" },
      { title: "Канцелярские принадлежности", href: "/catalog/personalnye/59571" },
      { title: "Визитницы", href: "/catalog/personalnye/18333" },
      { title: "Бейджи и аксессуары", href: "/catalog/personalnye/59572" },
      { title: "Настольные аксессуары", href: "/catalog/personalnye/59570" },
    ],
  },
  {
    id: "nagrady",
    title: "Награды",
    href: "/catalog/nagrady",
    children: [
      { title: "Стелы", href: "/catalog/nagrady/stely" },
      { title: "Плакетки", href: "/catalog/nagrady/plaketki" },
      { title: "Медали", href: "/catalog/nagrady/medali" },
      { title: "Кубки", href: "/catalog/nagrady/kubki" },
      { title: "Наградные плакетки", href: "/catalog/nagrady/28917" },
    ],
  },
  {
    id: "puteshestvie-i-otdy-x",
    title: "Путешествие и отдых",
    href: "/catalog/puteshestvie-i-otdy-x",
    children: [
      { title: "Бутылки и фляжки", href: "/catalog/puteshestvie-i-otdy-x/s-butylka-dlya-vody" },
      { title: "Спортивные товары", href: "/catalog/puteshestvie-i-otdy-x/otdyh-sportivnye-tovary" },
      { title: "Туристические принадлежности", href: "/catalog/puteshestvie-i-otdy-x/otdyh-turisticheskiye-prinadlezhnosti" },
      { title: "Автотовары", href: "/catalog/puteshestvie-i-otdy-x/otdyh-avtoprinadlejnosti" },
      { title: "Инструменты", href: "/catalog/puteshestvie-i-otdy-x/nozhi-i-instrumenty" },
      { title: "Игры и головоломки", href: "/catalog/puteshestvie-i-otdy-x/igry-podarki-detyam" },
    ],
  },
  {
    id: "promo",
    title: "Промо-сувениры",
    href: "/catalog/promo",
    children: [
      { title: "Светоотражатели", href: "/catalog/promo/promo-svetootrajateli" },
      { title: "Брелоки", href: "/catalog/promo/promo-plastikovye-brelki" },
      { title: "Бейджы", href: "/catalog/promo/2435" },
      { title: "Антистрессы", href: "/catalog/promo/promo-antistressy" },
      { title: "Зажигалки", href: "/catalog/promo/promo-zajigalki" },
      { title: "Зеркала", href: "/catalog/promo/promo-zerkala" },
      { title: "Товары для животных", href: "/catalog/promo/tovary-dlya-zhivotny-x" },
      { title: "Аксессуары", href: "/catalog/promo/promo-promoprodukciya" },
      { title: "Кастом360", href: "/catalog/promo/12303" },
      { title: "Трендовые цвета", href: "/catalog/promo/11019" },
      { title: "Товары для лета", href: "/catalog/promo/52975" },
    ],
  },
  {
    id: "vip",
    title: "Элитные подарки",
    href: "/catalog/vip",
    children: [
      { title: "Знаки внимания", href: "/catalog/vip/vip-znaki-vnimaniya" },
      { title: "Подарочные книги", href: "/catalog/vip/vip-podarochnye-knigi" },
      { title: "Для курения", href: "/catalog/vip/2446" },
      { title: "Гербы", href: "/catalog/vip/gerby-" },
      { title: "Глобусы", href: "/catalog/vip/4173" },
      { title: "Шкатулки для украшений", href: "/catalog/vip/4172" },
    ],
  },
  {
    id: "suveniry-k-prazdnikam",
    title: "Сувениры к праздникам",
    href: "/catalog/suveniry-k-prazdnikam",
    children: [
      { title: "14 февраля", href: "/catalog/suveniry-k-prazdnikam/14-fevralya" },
      { title: "23 февраля", href: "/catalog/suveniry-k-prazdnikam/suveniry-k-23-fevralya" },
      { title: "8 марта", href: "/catalog/suveniry-k-prazdnikam/suveniry-k-8-marta" },
      { title: "День Победы", href: "/catalog/suveniry-k-prazdnikam/den-pobedy-9-maya" },
      { title: "Значимые даты", href: "/catalog/suveniry-k-prazdnikam/podarki-na-den-energetika" },
      { title: "Подарки по профессиям", href: "/catalog/suveniry-k-prazdnikam/podarki-avtomobilistu" },
      { title: "Подарки детям", href: "/catalog/suveniry-k-prazdnikam/den-zashhity-detey" },
      { title: "Для компании и коллег", href: "/catalog/suveniry-k-prazdnikam/podarki-kollege" },
      { title: "Эко-подарки", href: "/catalog/suveniry-k-prazdnikam/eko-podarki" },
      { title: "Подарки на День медицинского работника", href: "/catalog/suveniry-k-prazdnikam/59582" },
      { title: "Товары для животных", href: "/catalog/suveniry-k-prazdnikam/10962" },
      { title: "Подарки на День строителя", href: "/catalog/suveniry-k-prazdnikam/59581" },
    ],
  },
  {
    id: "novyy-god",
    title: "Новогодние подарки",
    href: "/catalog/novyy-god",
    children: [
      { title: "Символ года", href: "/catalog/novyy-god/novyy-god-simvol-goda" },
      { title: "Елочные игрушки", href: "/catalog/novyy-god/novogodnie-igrushki" },
      { title: "Свечи и подсвечники", href: "/catalog/novyy-god/s-novogodnie-svechi" },
      { title: "Вязаная одежда", href: "/catalog/novyy-god/teplye-podarki" },
      { title: "Наборы", href: "/catalog/novyy-god/s-novogodnie-nabory" },
      { title: "Упаковка для подарков", href: "/catalog/novyy-god/upakovka-dlya-novogodnih-podarkov" },
      { title: "Оригинальные календари", href: "/catalog/novyy-god/novyy-god-originalnye-kalendari" },
      { title: "Новогодний стол", href: "/catalog/novyy-god/novyy-god-novogodniy-stol" },
      { title: "Елочные шары", href: "/catalog/novyy-god/s-novogodnie-shary" },
      { title: "Новогодние гирлянды и светильники", href: "/catalog/novyy-god/59580" },
      { title: "Украшения для офиса к новому году", href: "/catalog/novyy-god/59578" },
      { title: "Новогодние елки с логотипом", href: "/catalog/novyy-god/59579" },
    ],
  },
  {
    id: "chasy",
    title: "Часы и метеостанции",
    href: "/catalog/chasy",
    children: [
      { title: "Настенные часы", href: "/catalog/chasy/chasy-nastennye" },
      { title: "Наручные часы", href: "/catalog/chasy/chasy-naruchnye" },
      { title: "Настольные часы", href: "/catalog/chasy/chasy-nastolnye" },
      { title: "Метеостанции", href: "/catalog/chasy/meteostanczii" },
    ],
  },
  {
    id: "uhod-i-zdorovie",
    title: "Уход и здоровье",
    href: "/catalog/uhod-i-zdorovie",
    children: [
      { title: "Косметички", href: "/catalog/uhod-i-zdorovie/2331" },
      { title: "Грелки и кулеры", href: "/catalog/uhod-i-zdorovie/2335" },
      { title: "Маникюрные наборы", href: "/catalog/uhod-i-zdorovie/2340" },
      { title: "Личная гигиена", href: "/catalog/uhod-i-zdorovie/2376" },
    ],
  },
  {
    id: "detyam",
    title: "Детям",
    href: "/catalog/detyam",
    children: [
      { title: "Детская одежда", href: "/catalog/detyam/detskaya-odejda" },
      { title: "Всё для рисования", href: "/catalog/detyam/2323" },
      { title: "Мягкие игрушки", href: "/catalog/detyam/2365" },
      { title: "Игры и аксессуары", href: "/catalog/detyam/2389" },
      { title: "Электроника", href: "/catalog/detyam/2439" },
      { title: "Рюкзаки", href: "/catalog/detyam/5733" },
      { title: "Карандаши и ручки", href: "/catalog/detyam/37361" },
      { title: "Игры", href: "/catalog/detyam/50788" },
    ],
  },
];
